project:
  type: website
  output-dir: .

website:
  title: "My Research Project"
  navbar:
    left:
      - href: handnote.qmd
        text: "Handnote"

format:
  html:
    theme: cosmo
    embed-resources: true
    toc: true